config/routes.rb
Rails.application.routes.draw do

  constraints(LoggedInConstraint.new) do
    root :to => 'posts#showall'
    get 'login', to: redirect('/')
    get 'newpost' => 'posts#new'
    get 'posts' => 'posts#showall'
    get 'signup', to: redirect('/')
  end

  root :to => redirect('login')

  
  get 'post/:id' => 'posts#show'

  post '/newpost' => 'posts#create'

  resources :posts, path: "post"

  get 'signup' => 'users#new', :anchor => "form1-8"

  resources :users, path: "user"

  
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  resources :sessions, path: "session"

  get '*path' => redirect('login')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user

    serialize :tags, Array
    serialize :extdata, Array

    def tags=(x)
        write_attribute(:tags, x.split(/ *, */))
    end

    def extdata=(x)
        write_attribute(:extdata, x.split(/ *, */))
    end
end

app/models/session.rb
class Session < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password

    validates :password, length: {minimum: 8}

    has_many :posts
    has_many :sessions

    serialize :likes, Array
    serialize :dislikes, Array

    def to_param
        username
    end
    
    def likes=(x)
        write_attribute(:likes, x.split(/ *, */))
    end

    def dislikes=(x)
        write_attribute(:dislikes, x.split(/ *, */))
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
        @current_user = User.find_by_id(session[:user_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
        @title = "New Post // The Komplex"
    end

    def create
        @post = current_user.posts.new(post_params)
        if @post.save
            redirect_to '/post/' + @post.id.to_s
        else
            redirect_to '/newpost'
        end
    end

    def show
        @post = Post.find(params[:id])
        @title = @post.title + " // The Komplex"
    end

    def showall
        @posts = Post.limit(20).reverse
        @title = "Your Feed // The Komplex"
    end
        
    private
        def post_params
            params.permit(:user_id, :posttype, :title, :extdata, :content, :tags)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end

    def create
        @user = User.find_by_email(params[:session][:email])
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            redirect_to '/'
        else
            redirect_to '/login'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to '/'
    end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/'
        else
            redirect_to '/signup'
        end
    end

    def show
        @user = User.find_by_username(params[:id])
        @title = @user.username + " // The Komplex"
    end  

    private
        def user_params
            params.require(:user).permit(:fullname, :email, :username, :password, :password_confirmation, :likes, :dislikes)
        end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Site made with Mobirise Website Builder v3.12.1, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v3.12.1, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag "black-and-white-logo-optimised-transparent-icon-128x158.png" %>
  <meta name="description" content="">
  <title><%= @title || "The Komplex" %></title>
  
  
  
</head>
<body>
<section id="ext_menu-4">

    <nav class="navbar navbar-dropdown">
        <div class="container">

            <div class="mbr-table">
                <div class="mbr-table-cell">

                    <div class="navbar-brand">
                        <%= link_to "The KOMPLEX", root_path, :class => "navbar-caption text-primary" %>
                    </div>

                </div>

                <% unless current_user == nil %>

                <div class="mbr-table-cell">

                    <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                        <div class="hamburger-icon"></div>
                    </button>

                    <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar">
                    
                    <li class="nav-item"><%= link_to "YOUR FEED", root_path, :class => "nav-link link" %></li>
                    <li class="nav-item"><%= link_to "PROFILE", user_path(current_user), :class => "nav-link link" %></li>
                    <li class="nav-item"><%= link_to "SETTINGS", root_path, :class => "nav-link link" %></li>
                    <li class="nav-item"><%= link_to "LOGOUT", logout_url, :class => "nav-link link", :method => :delete %></li>
                    <li class="nav-item nav-btn"><%= link_to "NEWPOST", newpost_url, :class => "nav-link btn btn-primary" %></li>
                    
                    </ul>


                    <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                        <div class="close-icon"></div>
                    </button>

                </div>

                <% end %>
            </div>

        </div>
    </nav>

</section>


<!-- specific page content will render here -->
<%= yield %>
  
  
  <input name="animation" type="hidden">
  </body>
</html>

app/views/pages/home.html.erb
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>The Komplex</title>
</head>

<body>
  <h1>The Komplex</h1>
  <p>This is a social network, with algorithmic sorting based on the things you like and the things you don't.</p>
</body>
</html>

app/views/posts/_post.html.erb
<section class="engine"><a rel="external" href="https://mobirise.com">mobirise.com</a></section><section class="mbr-section mbr-section__container article mbr-after-navbar" id="header3-e" style="background-color: rgb(255, 255, 255); padding-top: 100px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">
                <% if request.path == "/post/" + post.id.to_s %>
                    <%= post.title %>
                <% else %>
                    <%= link_to post.title, post_path(post), {:style => 'color:#000000;'} %>
                <% end %>
                </h3>
                <small class="mbr-section-subtitle"><%= link_to post.user.username, user_path(post.user) %><%= post.created_at.strftime(" posted %e %B %Y, %l:%M %p %Z") %></small>
            </div>
        </div>
    </div>
</section>

<section class="mbr-gallery mbr-section mbr-section-nopadding mbr-slider-carousel" id="gallery1-g" data-filter="false" style="background-color: rgb(255, 255, 255); padding-top: 0rem; padding-bottom: 0rem;">
    <!-- Filter -->
    

    <!-- Gallery -->
    <div class="mbr-gallery-row">
        <div class=" mbr-gallery-layout-default">
            <div>
                <div>                            
                    <% post.extdata.each do |data| %>
                        <div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p0" data-video-url="false">
                            <div href="#lb-gallery1-g" data-slide-to="0" data-toggle="modal">

                                <%= image_tag data %>
                            
                                <span class="icon-focus"></span>
                            
                            </div>
                        </div>
                    <% end %>    

                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <!-- Lightbox -->
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery1-g">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                <!--
                    <ol class="carousel-indicators">
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-g" class=" active" data-slide-to="0"></li><li data-app-prevent-settings="" data-target="#lb-gallery1-g" data-slide-to="1"></li>
                    </ol>
                
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <%= image_tag post.extdata %>
                        </div>
                    </div>
-->
                    <% if post.extdata.length > 1 %>
                    <a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery1-g">
                        <span class="icon-prev" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery1-g">
                        <span class="icon-next" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    <% end %>

                    <a class="close" href="#" role="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>



<section class="mbr-section article mbr-section__container" id="content1-h" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">

    <div class="container">
        <div class="row">
            <div class="col-xs-12 lead"><p><%= post.content %></p></div>
        </div>
    </div>

</section>

<section class="mbr-section article mbr-section__container" id="content2-i" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">

    <div class="container">
        <div class="row">
            <div class="col-xs-12 lead"><blockquote>
                <% post.tags.each do |tag| %>
                    <%= "##{tag}" %>
                <% end %>                
            </blockquote></div>
        </div>
    </div>

</section>

app/views/posts/new.html.erb
<head>
    <style>
        #buttons {
            margin: 0px;
            padding: 0px;
        }

        #buttons li {
            display: inline;
        }

        #buttons input[type="radio"] {
            display: none;
        }

        #buttons input[type="radio"]:checked + label,
        .Checked + label {
            background: #535353;
            color: #fff
        }

        #buttons label {
            cursor: pointer;
        }

        #text {
            display: none;
        }

        #photo {
            display: none;
        }

        #video {
            display: none;
        }

        #link {
            display: none;
        }
    </style>

<%= javascript_tag do %>
function openForm(evt, posttype) {
    var forms, formselect;

    forms = document.getElementsByClassName("form");
    for (var i = 0; i < forms.length; i++) {
        forms[i].style.display = "none";
    };

    formselects = document.getElementsByClassName("formselect");
    for (var j = 0; i < formselects.length; j++) {
        formselects[j].className = formselects[j].className.replace(":target", "");
    };

    document.getElementById(posttype).style.display = "block";
    evt.currentTarget.className += ":target";
};
<% end %>

</head>

<section class="engine"><a rel="external" href="https://mobirise.com">mobirise.com</a></section><section class="mbr-section mbr-section__container article mbr-after-navbar" id="header3-e" style="background-color: rgb(255, 255, 255); padding-top: 100px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">New Post</h3>
                <small class="mbr-section-subtitle">Create a new post.</small>
            </div>
        </div>
    </div>
</section>


<section class="mbr-section mbr-section__container" id="buttons1-q" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul class="text-xs-center" id="buttons">
                <li>
                <input type="radio" name="buttons" class="btn btn-black-outline formselect" id='textselect' onclick="openForm(event, 'text')"/>
                <label for="textselect" class="btn btn-black-outline">TEXT</label>
                </li>
                <li>
                <input type="radio" name="buttons" class="btn btn-black-outline formselect" id='photoselect' onclick="openForm(event, 'photo')"/>
                <label for="photoselect" class="btn btn-black-outline">PHOTO</label>
                </li>
                <li>
                <input type="radio" name="buttons" class="btn btn-black-outline formselect" id='videoselect' onclick="openForm(event, 'video')"/>
                <label for="videoselect" class="btn btn-black-outline">VIDEO</label>
                </li>
                <li>
                <input type="radio" name="buttons" class="btn btn-black-outline formselect" id='linkselect' onclick="openForm(event, 'link')"/>
                <label for="linkselect" class="btn btn-black-outline">LINK</label>
                </li>
                </ul>
            </div>
        </div>
    </div>

</section>


<section class="mbr-section" id="form1-t" style="background-color: rgb(255, 255, 255); padding-top: 10px;">
    <div class="mbr-section mbr-section-nopadding">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-lg-10 col-lg-offset-1" data-form-type="formoid">

                    <div data-form-alert="true">
                        <div hidden="" data-form-alert-success="true" class="alert alert-form alert-success text-xs-center">Thanks for filling out form!</div>
                    </div>
                    
                        <!--<input type="hidden" value="hHN1/3wqgVb/951+u51IWB0OvciNmFG5tc2UYirI83zbjo5ajKEx3KPj0TThhW2TuTDwxk/5Z2lhW3GcrBSw7mWejVD4cavdwG705eAuVh+Yw9R571ETPxY/qVpJAnm2" data-form-email="true">-->

                        <%= form_for :post, url: '/post' do |f| %>

                        <div class="row row-sm-offset form" id="text">

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-title">Title</label>
                                    <%= f.text_field :title, :class => 'form-control', :name => 'title', :id => 'form1-t-title' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-content">Content</label>
                                    <%= f.text_area :content, :class => 'form-control', :name => 'content', :rows => '7', :id => 'form1-t-content', :required => 'true' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-tags">Tags</label>
                                    <%= f.text_field :tags, :class => 'form-control', :name => 'tags', :id => 'form1-t-tags', :required => 'true' %>
                                </div>
                            </div>

                            <div><%= f.submit "POST", class: "btn btn-primary" %></div>

                        </div>

                        <% end %>

                        <%= form_for :post, url: '/post' do |f| %>

                        <div class="row row-sm-offset form" id="photo">

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-extdata">Photo</label>
                                    <%= f.text_field :extdata, :class => 'form-control', :name => 'extdata', :id => 'form1-t-extdata', :required => 'true' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-title">Title</label>
                                    <%= f.text_field :title, :class => 'form-control', :name => 'title', :id => 'form1-t-title' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-content">Content</label>
                                    <%= f.text_area :content, :class => 'form-control', :name => 'content', :rows => '7', :id => 'form1-t-content' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-tags">Tags</label>
                                    <%= f.text_field :tags, :class => 'form-control', :name => 'tags', :id => 'form1-t-tags', :required => 'true' %>
                                </div>
                            </div>

                            <div><%= f.submit "POST", class: "btn btn-primary" %></div>

                        </div>

                        <% end %>

                        <%= form_for :post, url: '/post' do |f| %>

                        <div class="row row-sm-offset form" id="video">

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-extdata">Video</label>
                                    <%= f.text_field :extdata, :class => 'form-control', :name => 'extdata', :id => 'form1-t-extdata', :required => 'true'%>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-title">Title</label>
                                    <%= f.text_field :title, :class => 'form-control', :name => 'title', :id => 'form1-t-title' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-content">Content</label>
                                    <%= f.text_area :content, :class => 'form-control', :name => 'content', :rows => '7', :id => 'form1-t-content' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-tags">Tags</label>
                                    <%= f.text_field :tags, :class => 'form-control', :name => 'tags', :id => 'form1-t-tags', :required => 'true' %>
                                </div>
                            </div>

                            <div><%= f.submit "POST", class: "btn btn-primary" %></div>

                        </div>

                        <% end %>

                        <%= form_for :post, url: '/post' do |f| %>

                        <div class="row row-sm-offset form" id="link">

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-extdata">Link</label>
                                    <%= f.text_field :extdata, :class => 'form-control', :name => 'extdata', :id => 'form1-t-extdata', :required => 'true'%>
                                </div>
                            </div>


                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-title">Title</label>
                                    <%= f.text_field :title, :class => 'form-control', :name => 'title', :id => 'form1-t-title' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-content">Content</label>
                                    <%= f.text_area :content, :class => 'form-control', :name => 'content', :rows => '7', :id => 'form1-t-content' %>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-t-tags">Tags</label>
                                    <%= f.text_field :tags, :class => 'form-control', :name => 'tags', :id => 'form1-t-tags', :required => 'true' %>
                                </div>
                            </div>

                            <div><%= f.submit "POST", class: "btn btn-primary" %></div>

                        </div>

                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/posts/show.html.erb
<%= render(:partial => 'post', :locals => {:post => @post}) %>

app/views/posts/showall.html.erb
<% @posts.each do |post| %>
    <%= render 'post', :post => post %>
<% end %>

app/views/users/_new.html.erb
<section class="mbr-section" id="form1-8" style="background-color: rgb(255, 255, 255); padding-top: 120px; padding-bottom: 120px;">
    
    <div class="mbr-section mbr-section__container mbr-section__container--middle">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-xs-center">
                    <h3 class="mbr-section-title display-2">SIGN UP</h3>
                    <small class="mbr-section-subtitle">Create your Komplex account and begin seeing and sharing, just the things you like. Or <a href="login.html#form1-7">login</a> to your existing account.</small>
                </div>
            </div>
        </div>
    </div>
    
    <div class="mbr-section mbr-section-nopadding">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-lg-10 col-lg-offset-1" data-form-type="formoid">
       
                    <%= form_for(:user, url: users_url) do |f| %>

                        <div class="row row-sm-offset">

                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-8-email">Email</label>
                                    <%= f.email_field :email, :placeholder => "Email", :id => "form1-8-email", :class => "form-control" %>
                                </div>
                            </div>


                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-8-name">Name</label>
                                    <%= f.text_field :fullname, :placeholder => "Full Name", :id => "form1-8-name", :class => "form-control" %>
                                </div>
                            </div>


                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-8-phone">Password</label>
                                    <%= f.password_field :password, :placeholder => "Password", :id => "form1-8-password", :class => "form-control" %>
                            </div>

                        </div>

                        <div class="row row-sm-offset">

                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-8-name">Username</label>
                                    <%= f.text_field :username, :placeholder => "Username", :id => "form1-8-username", :class => "form-control" %>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-8-name">Likes</label>
                                    <%= f.text_field :likes, :placeholder => "Likes", :id => "form1-8-likes", :class => "form-control" %>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="form1-8-name">Dislikes</label>
                                    <%= f.text_field :dislikes, :placeholder => "Dislikes", :id => "form1-8-dislikes", :class => "form-control" %>
                                </div>
                            </div>

                        </div>

                        <div><%= f.submit "SIGNUP", class: "btn btn-primary", :type => "submit" %></div>

                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/users/_profile.html.erb
<section class="engine"><a rel="external" href="https://mobirise.com">mobirise.com</a></section><section class="mbr-section mbr-section__container article mbr-after-navbar" id="header3-e" style="background-color: rgb(255, 255, 255); padding-top: 100px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2"><%= user.username %></h3>
                <small class="mbr-section-subtitle"><%= user.fullname %></small>
            </div>
        </div>
    </div>
</section>


<section class="mbr-section article mbr-section__container" id="content6-o" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-6 lead"><p><strong>Likes:</strong>
                <% user.likes.each do |like| %>
                    <%= "##{like}" %>
                <% end %>
            </p></div>
            <div class="col-xs-12 col-md-6 lead"><p><strong>Dislikes:</strong>
                <% user.dislikes.each do |dislike| %>
                    <%= "##{dislike}" %>
                <% end %>
            </p></div>
        </div>
    </div>
</section>


<section class="mbr-cards mbr-section mbr-section-nopadding" id="features4-m" style="background-color: rgb(255, 255, 255);">
    <% user.posts.limit(3).reverse.each do |post| %>
        <div class="mbr-cards-row row">
                <div class="mbr-cards-col col-xs-12 col-lg-4" style="padding-top: 80px; padding-bottom: 80px;">
                    <div class="container">
                        <div class="card cart-block">
                            <% post.extdata.first do |extdata1| %>
                            <div class="card-img iconbox">
                                <%= link_to image_tag(extdata1), post_path(post), {:class => "etl-icon icon-phone mbr-iconfont mbr-iconfont-features4", :style => "color: black;"} %>
                            </div>
                            <% end %>
                            <div class="card-block">
                                <h4 class="card-title"><%= link_to post.title, post_path(post) %></h4>
                                <h5 class="card-subtitle"><%= post.created_at.strftime("posted %e %B %Y, %l:%M %p %Z") %></h5>
                                <p class="card-text"><%= truncate(post.content, :length => 250) %></p>
                                <p class="card-text"><b>
                                    <% post.tags.each do |tag| %>
                                        <%= "##{tag}" %>
                                    <% end %> 
                                </b></p>
                            </div>
                        </div>
                    </div>
                </div>
    <% end %>
</section>

app/views/users/new.html.erb
<%= render 'sessions/new' %>
<%= render 'users/new' %>

app/views/users/show.html.erb
<%= render(:partial => 'profile', :locals => {:user => @user}) %>